name: eco_quiz_app
description: An interactive environmental education quiz app for kids with colorful UI and animations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1
  confetti: ^0.7.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700

